/*********************************************************************************************
Created By: John Wrightsman
Email: john.wrightsman@revelanttech.com
Created: 11/20/2020
Description: Response to getting the MapBox geocoding API

Example response:

{
    "type": "FeatureCollection",
    "query": [
        "los",
        "angeles"
    ],
    "features": [
        {
            "id": "place.7397503093427640",
            "type": "Feature",
            "place_type": [
                "place"
            ],
            "relevance": 1,
            "properties": {
                "wikidata": "Q65"
            },
            "text": "Los Angeles",
            "place_name": "Los Angeles, California, United States",
            "bbox": [
                -118.521456965901,
                33.9018913203336,
                -118.121305008073,
                34.161440999758
            ],
            "center": [
                -118.2439,
                34.0544
            ],
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -118.2439,
                    34.0544
                ]
            },
            "context": [
                {
                    "id": "region.9803118085738010",
                    "wikidata": "Q99",
                    "short_code": "US-CA",
                    "text": "California"
                },
                {
                    "id": "country.19678805456372290",
                    "wikidata": "Q30",
                    "short_code": "us",
                    "text": "United States"
                }
            ]
        },
        {
            "id": "place.10952642230180310",
            "type": "Feature",
            "place_type": [
                "place"
            ],
            "relevance": 1,
            "properties": {
                "wikidata": "Q16910"
            },
            "text": "Los Ángeles",
            "place_name": "Los Ángeles, Bío Bío, Chile",
            "bbox": [
                -72.68248,
                -37.663862,
                -72.041277,
                -37.178368
            ],
            "center": [
                -72.35,
                -37.46667
            ],
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -72.35,
                    -37.46667
                ]
            },
            "context": [
                {
                    "id": "region.8544689811876870",
                    "wikidata": "Q2170",
                    "short_code": "CL-BI",
                    "text": "Bío Bío"
                },
                {
                    "id": "country.10394314763731110",
                    "wikidata": "Q298",
                    "short_code": "cl",
                    "text": "Chile"
                }
            ]
        },
        {
            "id": "poi.300647807514",
            "type": "Feature",
            "place_type": [
                "poi"
            ],
            "relevance": 1,
            "properties": {
                "foursquare": "439ec330f964a520102c1fe3",
                "wikidata": "Q8731",
                "landmark": true,
                "address": "1 World Way",
                "category": "airport",
                "maki": "airport"
            },
            "text": "Los Angeles International Airport (LAX)",
            "place_name": "Los Angeles International Airport (LAX), 1 World Way, Los Angeles, California 90045, United States",
            "center": [
                -118.406829,
                33.942912
            ],
            "geometry": {
                "coordinates": [
                    -118.406829,
                    33.942912
                ],
                "type": "Point"
            },
            "context": [
                {
                    "id": "neighborhood.33720",
                    "text": "Westchester"
                },
                {
                    "id": "postcode.15395803225252730",
                    "text": "90045"
                },
                {
                    "id": "place.7397503093427640",
                    "wikidata": "Q65",
                    "text": "Los Angeles"
                },
                {
                    "id": "region.9803118085738010",
                    "wikidata": "Q99",
                    "short_code": "US-CA",
                    "text": "California"
                },
                {
                    "id": "country.19678805456372290",
                    "wikidata": "Q30",
                    "short_code": "us",
                    "text": "United States"
                }
            ]
        },
        {
            "id": "locality.9858218050180310",
            "type": "Feature",
            "place_type": [
                "locality"
            ],
            "relevance": 1,
            "properties": {
                "wikidata": "Q390462"
            },
            "text": "Los Ángeles",
            "place_name": "Los Ángeles, Madrid, Madrid, Spain",
            "bbox": [
                -3.70707139897225,
                40.3456805018361,
                -3.6930253001356,
                40.3645357999689
            ],
            "center": [
                -3.69917,
                40.35667
            ],
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -3.69917,
                    40.35667
                ]
            },
            "context": [
                {
                    "id": "place.10708255346562040",
                    "wikidata": "Q2807",
                    "text": "Madrid"
                },
                {
                    "id": "region.9368530433562040",
                    "wikidata": "Q2807",
                    "text": "Madrid"
                },
                {
                    "id": "country.3373497261570100",
                    "wikidata": "Q29",
                    "short_code": "es",
                    "text": "Spain"
                }
            ]
        },
        {
            "id": "neighborhood.2104633",
            "type": "Feature",
            "place_type": [
                "neighborhood"
            ],
            "relevance": 1,
            "properties": {},
            "text": "Los Angeles Heights - Keystone",
            "place_name": "Los Angeles Heights - Keystone, San Antonio, Texas 78201, United States",
            "bbox": [
                -98.534942,
                29.453364,
                -98.514652,
                29.485214
            ],
            "center": [
                -98.52,
                29.47
            ],
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -98.52,
                    29.47
                ]
            },
            "context": [
                {
                    "id": "postcode.9559195398572850",
                    "text": "78201"
                },
                {
                    "id": "place.7333361243253710",
                    "wikidata": "Q975",
                    "text": "San Antonio"
                },
                {
                    "id": "region.12968715825342410",
                    "wikidata": "Q1439",
                    "short_code": "US-TX",
                    "text": "Texas"
                },
                {
                    "id": "country.19678805456372290",
                    "wikidata": "Q30",
                    "short_code": "us",
                    "text": "United States"
                }
            ]
        }
    ],
    "attribution": "NOTICE: © 2020 Mapbox and its suppliers. All rights reserved. Use of this data is subject to the Mapbox Terms of Service (https://www.mapbox.com/about/maps/). This response and the information it contains may not be retained. POI(s) provided by Foursquare."
}

*********************************************************************************************/
public without sharing class CCCAPIRespMapBoxGeocoding extends HttpResponseElement{
    
    /**
    * @description Set the response object
    */
    public CCCAPIRespMapBoxGeocoding(HttpResponse response) {
        setResponse(response);
    }

    /**
    * @description Object holding the response data
    */
    public class ServerResponse extends CCCServerResponse {
        @AuraEnabled public List<FeatureData> features { get; set; }

        public ServerResponse() {
            super();
            this.features = new List<FeatureData>();
        }
    }

    /**
    * @description Return the deserialized response JSON data
    */
    public ServerResponse getServerResponse() {
        ServerResponse response = new ServerResponse();

        try {
            response = (ServerResponse) JSON.deserialize(getBody(), ServerResponse.class);
            response.hasErrors = false;
        } catch(Exception e) {
            response.hasErrors = true;
            response.message = getBody();
        }
        
        return response;
    }

    public class FeatureData {
        public GeometryData geometry { get; set; }
    }

    public class GeometryData {
        public String type { get; set; }
        public List<Decimal> coordinates { get; set; }
    }

}