/*********************************************************************************************
Created By: Alan Oshry
Email: alan.oshry@revelanttech.com
Created: 01/26/2021
Description: Apex class representation of a Fetch A Business JSON request

Example Request: (No payload)

Changes:

*********************************************************************************************/
public without sharing class CCCAPIReqFetchABusiness extends HTTPRequestElement {

    // Default constructor
    public CCCAPIReqFetchABusiness() {
    }
}